Add unit tests for spark.utils.StringUtils
Diffblue-benchmarks/Perwendel-spark pull request #2
Opened 2019-07-29 14:26 UTC by ThomasPerkins1123

Hi,

I've analysed your code base and noticed that `spark.utils.StringUtils` is not fully tested.

I've written some tests that cover this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).

Hopefully, these tests should help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other particular classes that you consider important.

2019-07-30 09:57 UTC, paulkennethkent approved these changes

2019-07-30 16:18 UTC, petersear requested changes

2019-07-30 16:18 UTC, petersear commented on src/test/java/spark/utils/StringUtilsTest.java
> +        Assert.assertEquals("", StringUtils.getFilename("///////"));
Add a test so that an apparently real file name is returned?

2019-07-30 16:18 UTC, petersear commented on src/test/java/spark/utils/StringUtilsTest.java
> +        Assert.assertFalse(StringUtils.isEmpty(0));
Shouldn't we be passing a string? Admittedly, the code returns true in this case.

2019-07-30 16:18 UTC, petersear commented on src/test/java/spark/utils/StringUtilsTest.java
> +        Assert.assertFalse(StringUtils.isEmpty(0));
Could also test for `""` for completeness.

2019-07-30 16:18 UTC, petersear commented on src/test/java/spark/utils/StringUtilsTest.java
> +        Assert.assertFalse(StringUtils.isNotBlank(null));
Could also test for `""` for completeness.

2019-07-30 16:18 UTC, petersear commented on src/test/java/spark/utils/StringUtilsTest.java
> +	public void testIsNotEmpty() {
I would expect to see the test for `isNotEmpty()` next to the test for `isEmpty()` - same with `isBlank()` and `isNotBlank()` as is the case in the source.
You could go further (if you want :-) and order the test methods to match the source methods.

2019-07-30 16:18 UTC, petersear commented on src/test/java/spark/utils/StringUtilsTest.java
> +		Assert.assertEquals("", StringUtils.toString(new byte[0], "UTF-8"));
Could we expect a non-empty string?

2019-07-30 16:18 UTC, petersear commented on src/test/java/spark/utils/StringUtilsTest.java
> +        Assert.assertEquals("foo:/../Bar", StringUtils.cleanPath("foo:/foo/../../Bar"));
Add a blank line between different assert types.

2019-07-31 09:32 UTC, petersear approved these changes

2019-09-04 08:50 UTC, closed without merging